'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Teltbook1

    '''<summary>
    '''percheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents percheck As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''Vokscheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Vokscheck As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''Chilcheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Chilcheck As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''Sengcheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sengcheck As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''macheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents macheck As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''HiChk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiChk As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''Lavchk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lavchk As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
End Class
